//LOCALHOST
### GET all users
GET http://localhost:3001/users



### Create contact
POST http://localhost:3001/users HTTP/1.1
content-type: application/json
{
    "name": "Sunkern",
    "type": "grass",
    "number": "102",
    "worldNumber": "191"
}


### DELETE

DELETE http://localhost:3000/users/<id_user>